import type { BarrioInput } from '../../models/barrio.model.js';

/** @TODO - use this instead of the DB for static lookup? */
const BarriosData: BarrioInput[] = [
	{
		barrioId: 1,
		parentId: 0,
		officialName: 'Ciutat Vella',
		officialNameAccentless: 'Ciutat Vella',
		urlSlug: '/ciutat-vella',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 2,
		parentId: 0,
		officialName: "L'Eixample",
		officialNameAccentless: "L'Eixample",
		urlSlug: '/leixample',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 3,
		parentId: 0,
		officialName: 'Sants-Montjuïc',
		officialNameAccentless: 'Sants-Montjuic',
		urlSlug: '/sants-montjuic',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 4,
		parentId: 0,
		officialName: 'Les Corts',
		officialNameAccentless: 'Les Corts',
		urlSlug: '/les-corts',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 5,
		parentId: 0,
		officialName: 'Sarrià-Sant Gervasi',
		officialNameAccentless: 'Sarria-Sant Gervasi',
		urlSlug: '/sarria-sant-gervasi',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 6,
		parentId: 0,
		officialName: 'Gràcia',
		officialNameAccentless: 'Gracia',
		urlSlug: '/gracia',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 7,
		parentId: 0,
		officialName: 'Horta-Guinardó',
		officialNameAccentless: 'Horta-Guinardo',
		urlSlug: '/horta-guinardo',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 8,
		parentId: 0,
		officialName: 'Nou Barris',
		officialNameAccentless: 'Nou Barris',
		urlSlug: '/nou-barris',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 9,
		parentId: 0,
		officialName: 'Sant Andreu',
		officialNameAccentless: 'Sant Andreu',
		urlSlug: '/sant-andreu',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 10,
		parentId: 0,
		officialName: 'Sant Martí',
		officialNameAccentless: 'Sant Marti',
		urlSlug: '/sant-marti',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 11,
		parentId: 1,
		officialName: 'El Raval',
		officialNameAccentless: 'El Raval',
		urlSlug: '/el-raval',
		barrioZone: 1,
		centre: {
			lat: 41.37571366266082,
			lng: 2.170400619506836,
		},
	},
	{
		barrioId: 12,
		parentId: 1,
		officialName: 'El Barri Gòtic',
		officialNameAccentless: 'El Barri Gotic',
		urlSlug: '/el-barri-gotic',
		barrioZone: 1,
		centre: {
			lat: 41.37719499766946,
			lng: 2.1796703338623047,
		},
	},
	{
		barrioId: 13,
		parentId: 1,
		officialName: 'Sant Pere, Santa Caterina i la Ribera',
		officialNameAccentless: 'Sant Pere, Santa Caterina i la Ribera',
		urlSlug: '/sant-pere-santa-caterina-i-la-ribera',
		barrioZone: 1,
		centre: {
			lat: 41.384601166653376,
			lng: 2.1838760375976562,
		},
	},
	{
		barrioId: 14,
		parentId: 1,
		officialName: 'La Barceloneta',
		officialNameAccentless: 'La Barceloneta',
		urlSlug: '/la-barceloneta',
		barrioZone: 1,
		centre: {
			lat: 41.37526281487492,
			lng: 2.1915149688720703,
		},
	},
	{
		barrioId: 15,
		parentId: 2,
		officialName: "L'Antiga Esquerra de l'Eixample",
		officialNameAccentless: "L'Antiga Esquerra de l'Eixample",
		urlSlug: '/lantiga-esquerra-de-leixample',
		barrioZone: 1,
		centre: {
			lat: 41.38855,
			lng: 2.1573,
		},
	},
	{
		barrioId: 16,
		parentId: 2,
		officialName: "La Nova Esquerra de l'Eixample",
		officialNameAccentless: "La Nova Esquerra de l'Eixample",
		urlSlug: '/la-nova-esquerra-de-leixample',
		barrioZone: 1,
		centre: {
			lat: 41.38373,
			lng: 2.14747,
		},
	},
	{
		barrioId: 17,
		parentId: 2,
		officialName: "La Dreta de l'Eixample",
		officialNameAccentless: "La Dreta de l'Eixample",
		urlSlug: '/la-dreta-de-leixample',
		barrioZone: 1,
		centre: {
			lat: 41.3963,
			lng: 2.16538,
		},
	},
	{
		barrioId: 18,
		parentId: 2,
		officialName: 'El Fort Pienc',
		officialNameAccentless: 'El Fort Pienc',
		urlSlug: '/el-fort-pienc',
		barrioZone: 1,
		centre: {
			lat: 41.3981,
			lng: 2.18187,
		},
	},
	{
		barrioId: 19,
		parentId: 2,
		officialName: 'La Sagrada Família',
		officialNameAccentless: 'La Sagrada Familia',
		urlSlug: '/la-sagrada-familia',
		barrioZone: 1,
		centre: {
			lat: 41.40448,
			lng: 2.17572,
		},
	},
	{
		barrioId: 20,
		parentId: 2,
		officialName: 'Sant Antoni',
		officialNameAccentless: 'Sant Antoni',
		urlSlug: '/sant-antoni',
		barrioZone: 1,
		centre: {
			lat: 41.37726,
			lng: 2.15853,
		},
	},
	{
		barrioId: 21,
		parentId: 3,
		officialName: 'La Bordeta',
		officialNameAccentless: 'La Bordeta',
		urlSlug: '/la-bordeta',
		barrioZone: 1,
		centre: {
			lat: 41.36324,
			lng: 2.13269,
		},
	},
	{
		barrioId: 22,
		parentId: 3,
		officialName: 'La Font de la Guatlla',
		officialNameAccentless: 'La Font de la Guatlla',
		urlSlug: '/la-font-de-la-guatlla',
		barrioZone: 1,
		centre: {
			lat: 41.36607,
			lng: 2.14428,
		},
	},
	{
		barrioId: 23,
		parentId: 3,
		officialName: 'Hostafrancs',
		officialNameAccentless: 'Hostafrancs',
		urlSlug: '/hostafrancs',
		barrioZone: 1,
		centre: {
			lat: 41.37409,
			lng: 2.14534,
		},
	},
	{
		barrioId: 24,
		parentId: 3,
		officialName: 'La Marina de Port',
		officialNameAccentless: 'La Marina de Port',
		urlSlug: '/la-marina-de-port',
		barrioZone: 1,
		centre: {
			lat: 41.35886,
			lng: 2.13765,
		},
	},
	{
		barrioId: 25,
		parentId: 3,
		officialName: 'La Marina del Prat Vermell',
		officialNameAccentless: 'La Marina del Prat Vermell',
		urlSlug: '/la-marina-del-prat-vermell',
		barrioZone: 1,
		centre: {
			lat: 41.34706,
			lng: 2.13413,
		},
	},
	{
		barrioId: 26,
		parentId: 3,
		officialName: 'El Poble-sec',
		officialNameAccentless: 'El Poble-sec',
		urlSlug: '/el-poble-sec',
		barrioZone: 1,
		centre: {
			lat: 41.3703,
			lng: 2.16562,
		},
	},
	{
		barrioId: 27,
		parentId: 3,
		officialName: 'Sants',
		officialNameAccentless: 'Sants',
		urlSlug: '/sants',
		barrioZone: 1,
		centre: {
			lat: 41.37433,
			lng: 2.13735,
		},
	},
	{
		barrioId: 28,
		parentId: 3,
		officialName: 'Sants-Badal',
		officialNameAccentless: 'Sants-Badal',
		urlSlug: '/sants-badal',
		barrioZone: 1,
		centre: {
			lat: 41.37303,
			lng: 2.12699,
		},
	},
	{
		barrioId: 29,
		parentId: 4,
		officialName: 'Les Corts',
		officialNameAccentless: 'Les Corts',
		urlSlug: '/les-corts',
		barrioZone: 1,
		centre: {
			lat: 41.38537,
			lng: 2.13616,
		},
	},
	{
		barrioId: 30,
		parentId: 4,
		officialName: 'La Maternitat i Sant Ramon',
		officialNameAccentless: 'La Maternitat i Sant Ramon',
		urlSlug: '/la-maternitat-i-sant-ramon',
		barrioZone: 1,
		centre: {
			lat: 41.37935,
			lng: 2.11311,
		},
	},
	{
		barrioId: 31,
		parentId: 4,
		officialName: 'Pedralbes',
		officialNameAccentless: 'Pedralbes',
		urlSlug: '/pedralbes',
		barrioZone: 1,
		centre: {
			lat: 41.3903,
			lng: 2.10912,
		},
	},
	{
		barrioId: 32,
		parentId: 5,
		officialName: 'El Putxet i el Farró',
		officialNameAccentless: 'El Putxet i el Farro',
		urlSlug: '/el-putxet-i-el-farro',
		barrioZone: 1,
		centre: {
			lat: 41.40758,
			lng: 2.14379,
		},
	},
	{
		barrioId: 33,
		parentId: 5,
		officialName: 'Sarrià',
		officialNameAccentless: 'Sarria',
		urlSlug: '/sarria',
		barrioZone: 1,
		centre: {
			lat: 41.3969,
			lng: 2.12038,
		},
	},
	{
		barrioId: 34,
		parentId: 5,
		officialName: 'Sant Gervasi - la Bonanova',
		officialNameAccentless: 'Sant Gervasi - la Bonanova',
		urlSlug: '/sant-gervasi-la-bonanova',
		barrioZone: 1,
		centre: {
			lat: 41.4071,
			lng: 2.12702,
		},
	},
	{
		barrioId: 35,
		parentId: 5,
		officialName: 'Sant Gervasi - Galvany',
		officialNameAccentless: 'Sant Gervasi - Galvany',
		urlSlug: '/sant-gervasi-galvany',
		barrioZone: 1,
		centre: {
			lat: 41.3973,
			lng: 2.14591,
		},
	},
	{
		barrioId: 36,
		parentId: 5,
		officialName: 'Les Tres Torres',
		officialNameAccentless: 'Les Tres Torres',
		urlSlug: '/les-tres-torres',
		barrioZone: 1,
		centre: {
			lat: 41.39779,
			lng: 2.13152,
		},
	},
	{
		barrioId: 37,
		parentId: 5,
		officialName: 'Vallvidrera, el Tibidabo i les Planes',
		officialNameAccentless: 'Vallvidrera, el Tibidabo i les Planes',
		urlSlug: '/vallvidrera-el-tibidabo-i-les-planes',
		barrioZone: 1,
		centre: {
			lat: 41.41731,
			lng: 2.09103,
		},
	},
	{
		barrioId: 38,
		parentId: 6,
		officialName: 'La Vila de Gràcia',
		officialNameAccentless: 'La Vila de Gracia',
		urlSlug: '/la-vila-de-gracia',
		barrioZone: 1,
		centre: {
			lat: 41.40199,
			lng: 2.15368,
		},
	},
	{
		barrioId: 39,
		parentId: 6,
		officialName: "El Camp d'en Grassot i Gràcia Nova",
		officialNameAccentless: "El Camp d'en Grassot i Gracia Nova",
		urlSlug: '/el-camp-den-grassot-i-gracia-nova',
		barrioZone: 1,
		centre: {
			lat: 41.40466,
			lng: 2.1659,
		},
	},
	{
		barrioId: 40,
		parentId: 6,
		officialName: 'La Salut',
		officialNameAccentless: 'La Salut',
		urlSlug: '/la-salut',
		barrioZone: 1,
		centre: {
			lat: 41.40825,
			lng: 2.15651,
		},
	},
	{
		barrioId: 41,
		parentId: 6,
		officialName: 'El Coll',
		officialNameAccentless: 'El Coll',
		urlSlug: '/el-coll',
		barrioZone: 1,
		centre: {
			lat: 41.41539,
			lng: 2.14767,
		},
	},
	{
		barrioId: 42,
		parentId: 6,
		officialName: 'Vallcarca i els Penitents',
		officialNameAccentless: 'Vallcarca i els Penitents',
		urlSlug: '/vallcarca-i-els-penitents',
		barrioZone: 1,
		centre: {
			lat: 41.41069,
			lng: 2.14303,
		},
	},
	{
		barrioId: 43,
		parentId: 7,
		officialName: 'El Baix Guinardó',
		officialNameAccentless: 'El Baix Guinardo',
		urlSlug: '/el-baix-guinardo',
		barrioZone: 1,
		centre: {
			lat: 41.4103,
			lng: 2.16794,
		},
	},
	{
		barrioId: 44,
		parentId: 7,
		officialName: 'El Guinardó',
		officialNameAccentless: 'El Guinardo',
		urlSlug: '/el-guinardo',
		barrioZone: 1,
		centre: {
			lat: 41.41875,
			lng: 2.17413,
		},
	},
	{
		barrioId: 45,
		parentId: 7,
		officialName: 'Can Baró',
		officialNameAccentless: 'Can Baro',
		urlSlug: '/can-baro',
		barrioZone: 1,
		centre: {
			lat: 41.41533,
			lng: 2.16108,
		},
	},
	{
		barrioId: 46,
		parentId: 7,
		officialName: 'El Carmel',
		officialNameAccentless: 'El Carmel',
		urlSlug: '/el-carmel',
		barrioZone: 1,
		centre: {
			lat: 41.42002,
			lng: 2.15489,
		},
	},
	{
		barrioId: 47,
		parentId: 7,
		officialName: "La Font d'en Fargues",
		officialNameAccentless: "La Font d'en Fargues",
		urlSlug: '/la-font-den-fargues',
		barrioZone: 1,
		centre: {
			lat: 41.42372,
			lng: 2.16529,
		},
	},
	{
		barrioId: 48,
		parentId: 7,
		officialName: 'Horta',
		officialNameAccentless: 'Horta',
		urlSlug: '/horta',
		barrioZone: 1,
		centre: {
			lat: 41.43491,
			lng: 2.15639,
		},
	},
	{
		barrioId: 49,
		parentId: 7,
		officialName: 'La Clota',
		officialNameAccentless: 'La Clota',
		urlSlug: '/la-clota',
		barrioZone: 1,
		centre: {
			lat: 41.42858,
			lng: 2.15398,
		},
	},
	{
		barrioId: 50,
		parentId: 7,
		officialName: 'Montbau',
		officialNameAccentless: 'Montbau',
		urlSlug: '/montbau',
		barrioZone: 1,
		centre: {
			lat: 41.43179,
			lng: 2.14135,
		},
	},
	{
		barrioId: 51,
		parentId: 7,
		officialName: 'Sant Genís dels Agudells',
		officialNameAccentless: 'Sant Genis dels Agudells',
		urlSlug: '/sant-genis-dels-agudells',
		barrioZone: 1,
		centre: {
			lat: 41.42414,
			lng: 2.12783,
		},
	},
	{
		barrioId: 52,
		parentId: 7,
		officialName: 'La Teixonera',
		officialNameAccentless: 'La Teixonera',
		urlSlug: '/la-teixonera',
		barrioZone: 1,
		centre: {
			lat: 41.42146,
			lng: 2.14372,
		},
	},
	{
		barrioId: 53,
		parentId: 7,
		officialName: "La Vall d'Hebron",
		officialNameAccentless: "La Vall d'Hebron",
		urlSlug: '/la-vall-dhebron',
		barrioZone: 1,
		centre: {
			lat: 41.42681,
			lng: 2.14553,
		},
	},
	{
		barrioId: 54,
		parentId: 8,
		officialName: 'Can Peguera',
		officialNameAccentless: 'Can Peguera',
		urlSlug: '/can-peguera',
		barrioZone: 1,
		centre: {
			lat: 41.43437,
			lng: 2.1662,
		},
	},
	{
		barrioId: 55,
		parentId: 8,
		officialName: 'Canyelles',
		officialNameAccentless: 'Canyelles',
		urlSlug: '/canyelles',
		barrioZone: 1,
		centre: {
			lat: 41.44328,
			lng: 2.16585,
		},
	},
	{
		barrioId: 56,
		parentId: 8,
		officialName: 'Ciutat Meridiana',
		officialNameAccentless: 'Ciutat Meridiana',
		urlSlug: '/ciutat-meridiana',
		barrioZone: 1,
		centre: {
			lat: 41.45944,
			lng: 2.17464,
		},
	},
	{
		barrioId: 57,
		parentId: 8,
		officialName: 'La Guineueta',
		officialNameAccentless: 'La Guineueta',
		urlSlug: '/la-guineueta',
		barrioZone: 1,
		centre: {
			lat: 41.43856,
			lng: 2.16819,
		},
	},
	{
		barrioId: 58,
		parentId: 8,
		officialName: 'Porta',
		officialNameAccentless: 'Porta',
		urlSlug: '/porta',
		barrioZone: 1,
		centre: {
			lat: 41.43399,
			lng: 2.17758,
		},
	},
	{
		barrioId: 59,
		parentId: 8,
		officialName: 'La Prosperitat',
		officialNameAccentless: 'La Prosperitat',
		urlSlug: '/la-prosperitat',
		barrioZone: 1,
		centre: {
			lat: 41.441,
			lng: 2.18361,
		},
	},
	{
		barrioId: 60,
		parentId: 8,
		officialName: 'Les Roquetes',
		officialNameAccentless: 'Les Roquetes',
		urlSlug: '/les-roquetes',
		barrioZone: 1,
		centre: {
			lat: 41.44682,
			lng: 2.17588,
		},
	},
	{
		barrioId: 61,
		parentId: 8,
		officialName: 'Torre Baró',
		officialNameAccentless: 'Torre Baro',
		urlSlug: '/torre-baro',
		barrioZone: 1,
		centre: {
			lat: 41.454498436576685,
			lng: 2.1759111000000075,
		},
	},
	{
		barrioId: 62,
		parentId: 8,
		officialName: 'La Trinitat Nova',
		officialNameAccentless: 'La Trinitat Nova',
		urlSlug: '/la-trinitat-nova',
		barrioZone: 1,
		centre: {
			lat: 41.44898,
			lng: 2.18349,
		},
	},
	{
		barrioId: 63,
		parentId: 8,
		officialName: 'El Turó de La Peira',
		officialNameAccentless: 'El Turo de La Peira',
		urlSlug: '/el-turo-de-la-peira',
		barrioZone: 1,
		centre: {
			lat: 41.43194,
			lng: 2.16754,
		},
	},
	{
		barrioId: 64,
		parentId: 8,
		officialName: 'Vallbona',
		officialNameAccentless: 'Vallbona',
		urlSlug: '/vallbona',
		barrioZone: 1,
		centre: {
			lat: 41.46312,
			lng: 2.18372,
		},
	},
	{
		barrioId: 65,
		parentId: 8,
		officialName: 'Verdum',
		officialNameAccentless: 'Verdum',
		urlSlug: '/verdum',
		barrioZone: 1,
		centre: {
			lat: 41.44144353123076,
			lng: 2.1758534550621107,
		},
	},
	{
		barrioId: 66,
		parentId: 8,
		officialName: 'Vilapicina i la Torre Llobeta',
		officialNameAccentless: 'Vilapicina i la Torre Llobeta',
		urlSlug: '/vilapicina-i-la-torre-llobeta',
		barrioZone: 1,
		centre: {
			lat: 41.428,
			lng: 2.17345,
		},
	},
	{
		barrioId: 67,
		parentId: 9,
		officialName: 'Baró de Viver',
		officialNameAccentless: 'Baro de Viver',
		urlSlug: '/baro-de-viver',
		barrioZone: 1,
		centre: {
			lat: 41.44308,
			lng: 2.19779,
		},
	},
	{
		barrioId: 68,
		parentId: 9,
		officialName: 'El Bon Pastor',
		officialNameAccentless: 'El Bon Pastor',
		urlSlug: '/el-bon-pastor',
		barrioZone: 1,
		centre: {
			lat: 41.43612,
			lng: 2.20515,
		},
	},
	{
		barrioId: 69,
		parentId: 9,
		officialName: 'El Congrés i els Indians',
		officialNameAccentless: 'El Congres i els Indians',
		urlSlug: '/el-congres-i-els-indians',
		barrioZone: 1,
		centre: {
			lat: 41.42245,
			lng: 2.18115,
		},
	},
	{
		barrioId: 70,
		parentId: 9,
		officialName: 'Navas',
		officialNameAccentless: 'Navas',
		urlSlug: '/navas',
		barrioZone: 1,
		centre: {
			lat: 41.41628,
			lng: 2.18547,
		},
	},
	{
		barrioId: 71,
		parentId: 9,
		officialName: 'Sant Andreu de Palomar',
		officialNameAccentless: 'Sant Andreu de Palomar',
		urlSlug: '/sant-andreu-de-palomar',
		barrioZone: 1,
		centre: {
			lat: 41.43305,
			lng: 2.18678,
		},
	},
	{
		barrioId: 72,
		parentId: 9,
		officialName: 'La Sagrera',
		officialNameAccentless: 'La Sagrera',
		urlSlug: '/la-sagrera',
		barrioZone: 1,
		centre: {
			lat: 41.42086,
			lng: 2.19122,
		},
	},
	{
		barrioId: 73,
		parentId: 9,
		officialName: 'La Trinitat Vella',
		officialNameAccentless: 'La Trinitat Vella',
		urlSlug: '/la-trinitat-vella',
		barrioZone: 1,
		centre: {
			lat: 41.45169,
			lng: 2.19293,
		},
	},
	{
		barrioId: 74,
		parentId: 10,
		officialName: 'El Besòs i el Maresme',
		officialNameAccentless: 'El Besos i el Maresme',
		urlSlug: '/el-besos-i-el-maresme',
		barrioZone: 1,
		centre: {
			lat: 41.41374,
			lng: 2.21505,
		},
	},
	{
		barrioId: 75,
		parentId: 10,
		officialName: 'El Clot',
		officialNameAccentless: 'El Clot',
		urlSlug: '/el-clot',
		barrioZone: 1,
		centre: {
			lat: 41.40973722830612,
			lng: 2.1903080499999987,
		},
	},
	{
		barrioId: 76,
		parentId: 10,
		officialName: "El Camp de l'Arpa del Clot",
		officialNameAccentless: "El Camp de l'Arpa del Clot",
		urlSlug: '/el-camp-de-larpa-del-clot',
		barrioZone: 1,
		centre: {
			lat: 41.41199874323254,
			lng: 2.1811938499999997,
		},
	},
	{
		barrioId: 77,
		parentId: 10,
		officialName: 'Diagonal Mar i el Front Marítim del Poblenou',
		officialNameAccentless: 'Diagonal Mar i el Front Maritim del Poblenou',
		urlSlug: '/diagonal-mar-i-el-front-maritim-del-poblenou',
		barrioZone: 1,
		centre: {
			lat: 41.405039627251384,
			lng: 2.2143934499999887,
		},
	},
	{
		barrioId: 78,
		parentId: 10,
		officialName: 'El Parc i la Llacuna del Poblenou',
		officialNameAccentless: 'El Parc i la Llacuna del Poblenou',
		urlSlug: '/el-parc-i-la-llacuna-del-poblenou',
		barrioZone: 1,
		centre: {
			lat: 41.398263145943744,
			lng: 2.189849900000013,
		},
	},
	{
		barrioId: 79,
		parentId: 10,
		officialName: 'El Poblenou',
		officialNameAccentless: 'El Poblenou',
		urlSlug: '/el-poblenou',
		barrioZone: 1,
		centre: {
			lat: 41.39956651309861,
			lng: 2.2022675999999137,
		},
	},
	{
		barrioId: 80,
		parentId: 10,
		officialName: 'Provençals del Poblenou',
		officialNameAccentless: 'Provencals del Poblenou',
		urlSlug: '/provencals-del-poblenou',
		barrioZone: 1,
		centre: {
			lat: 41.40994,
			lng: 2.203,
		},
	},
	{
		barrioId: 81,
		parentId: 10,
		officialName: 'Sant Martí de Provençals',
		officialNameAccentless: 'Sant Marti de Provencals',
		urlSlug: '/sant-marti-de-provencals',
		barrioZone: 1,
		centre: {
			lat: 41.41668827683491,
			lng: 2.198477550000007,
		},
	},
	{
		barrioId: 82,
		parentId: 10,
		officialName: 'La Verneda i la Pau',
		officialNameAccentless: 'La Verneda i la Pau',
		urlSlug: '/la-verneda-i-la-pau',
		barrioZone: 1,
		centre: {
			lat: 41.42399,
			lng: 2.20276,
		},
	},
	{
		barrioId: 83,
		parentId: 10,
		officialName: 'La Vila Olímpica del Poblenou',
		officialNameAccentless: 'La Vila Olimpica del Poblenou',
		urlSlug: '/la-vila-olimpica-del-poblenou',
		barrioZone: 1,
		centre: {
			lat: 41.39003028711036,
			lng: 2.1963494999999966,
		},
	},
	{
		barrioId: 84,
		parentId: 0,
		officialName: 'Other',
		officialNameAccentless: 'Other',
		urlSlug: '/other',
		barrioZone: -1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 85,
		parentId: 84,
		officialName: 'All Neighbourhoods',
		officialNameAccentless: 'All Neighbourhoods',
		urlSlug: '/all-neighbourhoods',
		barrioZone: 1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
	{
		barrioId: 86,
		parentId: 84,
		officialName: 'Outside Barcelona',
		officialNameAccentless: 'Outside Barcelona',
		urlSlug: '/outside-barcelona',
		barrioZone: -1,
		centre: {
			lat: 0,
			lng: 0,
		},
	},
];

export const getStaticBarrioById = (barrioId: number): BarrioInput | null => {
	return BarriosData.find((b) => b.barrioId === barrioId) ?? null;
};
