// export enum PersonaEnum {
//   WeekendBreakers = 'weekend_breakers',
//   EuropeanTourers = 'european_tourers',
//   Backpackers = 'backpackers',
//   ShoestringTravellers = 'shoestring_travellers',
//   FerryDaytrippers = 'ferry_daytrippers',
//   CultureSeekers = 'culture_seekers',
//   Newcomers = 'newcomers',
//   // ExpatsSettled = 'expats_setttled',
//   EventGoers = 'event_goers',
//   FamiliesWithChildren = 'families_with_children',
//   // FamiliesWithTeenagers = 'families_with_teenagers',
//   // SingleParents = 'single_parents',
//   // DigitalNomads = 'digital_nomads',
//   // LGBTQ = 'lgbtq',
//   // WheelchairUsers = 'wheelchair_users',
//   FoodiesWineies = 'foodies_wineies',
//   MuseumVisitors = 'museum_visitors',
//   BeachLovers = 'beach_lovers',
//   ArchitectureAdmirers = 'architecture_admirers',
//   // StagHenParty = 'stag_hen_party',
//   OutdoorsEnthusiasts = 'outdoors_enthusiasts',
//   TripAndExcursionists = 'trip_and_excursionists',
// }
export enum PersonaEnum {
	WeekendBreakers = 1,
	EuropeanTourers = 2,
	Backpackers = 3,
	ShoestringTravellers = 4,
	FerryDaytrippers = 5,
	CultureSeekers = 6,
	Newcomers = 7,
	// ExpatsSettled = 8,
	EventGoers = 9,
	FamiliesWithChildren = 10,
	// FamiliesWithTeenagers = 11,
	// SingleParents = 12,
	// DigitalNomads = 13,
	// LGBTQ = 14,
	// WheelchairUsers = 15,
	FoodiesWineies = 16,
	MuseumVisitors = 17,
	BeachLovers = 18,
	ArchitectureAdmirers = 19,
	// StagHenParty = 20,
	OutdoorsEnthusiasts = 21,
	DayTrippers = 22,
}
